@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "EdRecord Storage" #F4F6F6{
Interface EdRecordStorage <<Interface>>
Class JsonEdRecordStorage
Class JsonSerializableEdRecord
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" EdRecordStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> EdRecordStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonEdRecordStorage .up.|> EdRecordStorage
JsonEdRecordStorage ..> JsonSerializableEdRecord
JsonSerializableEdRecord --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
